on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

name: Check PR ENV

jobs:
  check:
    name: Check Env
    runs-on:  ubuntu-18.04
    strategy:
      fail-fast: false
      matrix:
        config:
        - { os: macOS-latest, r: '4.0', args: "--no-manual"}
    env:
      SUPER_SECRET: ${{ secrets.SLACK_API_TOKEN }}
    steps:
      - uses: r-lib/actions/setup-r@master
        with:
          r-version: ${{ matrix.config.r }}

      - name: Simple R Command
        run: |
          token <- Sys.getenv('SUPER_SECRET')
          print(token)
        shell: Rscript {0}
