on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master


name: Check PR ENV

jobs:
  check:
    name: Check Env
    runs-on:  ubuntu-18.04
    strategy:
      fail-fast: false
    env:
      SUPER_SECRET: "testing"
    steps:
    - uses: r-lib/actions/setup-r@master
        with:
          r-version: '4.0'

      - name: Simple R Command
        run: |
          token <- Sys.getenv('SUPER_SECRET')
          print(token)
        shell: Rscript {0}
